### ISSUE TITLE
Number Play - Publish 1.0 

### ISSUE THREAD

**Issue by chrisklus** [phetsims/number-play#11]
Place to link remaining issues for dev work needed to publish Number Play 1.0. Note that this is currently incomplete and more issues will be added/converted from TODOs.

features:

- [x] code sprint https://github.com/phetsims/number-play/issues/2
- [x] additions to compare screen https://github.com/phetsims/number-play/issues/25
- [ ] multitouch support https://github.com/phetsims/number-play/issues/6
- [x] grouping of play objects https://github.com/phetsims/number-play/issues/14
- [ ] new paper number UX https://github.com/phetsims/counting-common/issues/1
- [x] render paper number creator node with respect to number count https://github.com/phetsims/number-play/issues/23
- [x] add a button to read out the current text https://github.com/phetsims/number-play/issues/32

maintenance:

- [x] consolidate wrapping code for paper ones vs objects https://github.com/phetsims/number-play/issues/7
- [x] use Animation for paper ones https://github.com/phetsims/number-play/issues/8
- [x] update colors https://github.com/phetsims/number-play/issues/24
- [x] remove game screen https://github.com/phetsims/number-play/issues/34
- [ ] finish the lab screen https://github.com/phetsims/number-play/issues/33

bugs:

- [x] repelling objects https://github.com/phetsims/number-play/issues/10
- [x] ct assertion https://github.com/phetsims/number-play/issues/9
- [x] for loop that doesn't loop https://github.com/phetsims/number-play/issues/13

**Comment by chrisklus** [comment]
1.0 was published in May of 2022, closing.
